# Generated by Django 6.0.4 on 2026-04-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="disc_c",
            field=models.IntegerField(
                default=0,
                help_text="Score for Compliance dimension (0-100)",
                verbose_name="Соответствие",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="disc_d",
            field=models.IntegerField(
                help_text="Score for Dominance dimension (0-100)",
                null=True,
                verbose_name="Доминирование",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="disc_i",
            field=models.IntegerField(
                default=0,
                help_text="Score for Influence dimension (0-100)",
                verbose_name="Влияние",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="disc_s",
            field=models.IntegerField(
                default=0,
                help_text="Score for Steadiness dimension (0-100)",
                verbose_name="Стабильность",
            ),
        ),
    ]
