# Generated by Django 6.0.4 on 2026-04-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_disc_c_alter_user_disc_d_and_more"),
    ]

    operations = [
        migrations.AddField(model_name="user", name="image", field=models.ImageField(blank=True, null=True)),
    ]
