# Generated by Django 6.0.4 on 2026-04-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="motivational_profile",
        ),
        migrations.AddField(
            model_name="user",
            name="motype_ho",
            field=models.IntegerField(default=0, verbose_name="Хозяйский"),
        ),
        migrations.AddField(
            model_name="user",
            name="motype_in",
            field=models.IntegerField(default=0, verbose_name="Инструментальный"),
        ),
        migrations.AddField(
            model_name="user",
            name="motype_lu",
            field=models.IntegerField(default=0, verbose_name="Люмпенизированный"),
        ),
        migrations.AddField(
            model_name="user",
            name="motype_pa",
            field=models.IntegerField(default=0, verbose_name="Патриотический"),
        ),
        migrations.AddField(
            model_name="user",
            name="motype_pr",
            field=models.IntegerField(default=0, verbose_name="Профессиональный"),
        ),
    ]
