# Generated by Django 6.0.4 on 2026-04-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_motivational_profile_user_motype_ho_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="disc_d",
            field=models.IntegerField(
                default=0,
                help_text="Score for Dominance dimension (0-100)",
                null=True,
                verbose_name="Доминирование",
            ),
        ),
    ]
