# Generated by Django 6.0.4 on 2026-04-18 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.CreateModel(
            name="AIReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strengths", models.TextField()),
                ("weaknesses", models.TextField()),
                ("opportunities", models.TextField()),
                ("threats", models.TextField()),
                ("team_fit", models.TextField()),
                ("key_issues", models.TextField()),
                ("recommendations", models.TextField()),
                ("team_members_analysis", models.TextField()),
                (
                    "team",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.team"),
                ),
            ],
            options={
                "verbose_name": "Отзыв ИИ",
                "verbose_name_plural": "Отзывы ИИ",
            },
        ),
    ]
