# Generated by Django 6.0.4 on 2026-04-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_team_description_aireviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="aireviews",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2020-01-01"),
            preserve_default=False,
        ),
    ]
