# Generated by Django 6.0.4 on 2026-04-18 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_aireviews_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aireviews",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="core.team",
            ),
        ),
    ]
