# Generated by Django 6.0.4 on 2026-04-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_aireviews_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="motype_ho",
            field=models.IntegerField(default=0.2, verbose_name="Хозяйский"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="motype_in",
            field=models.IntegerField(default=0.2, verbose_name="Инструментальный"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="motype_lu",
            field=models.IntegerField(default=0.2, verbose_name="Люмпенизированный"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="motype_pa",
            field=models.IntegerField(default=0.2, verbose_name="Патриотический"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="motype_pr",
            field=models.IntegerField(default=0.2, verbose_name="Профессиональный"),
            preserve_default=False,
        ),
    ]
