# Generated by Django 6.0.4 on 2026-04-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_team_motype_ho_team_motype_in_team_motype_lu_and_more"),
        ("users", "0006_role_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="roles",
            field=models.ManyToManyField(to="users.role", verbose_name="Роли"),
        ),
    ]
