# Generated by Django 6.0.4 on 2026-04-19 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_team_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="users",
            field=models.ManyToManyField(blank=True, related_name="team_as_member", to=settings.AUTH_USER_MODEL),
        ),
    ]
